server:
  port: 18080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud_user?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Taipei
    username: yesee
    password: yesee
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      break-after-acquire-failure: true
      connection-error-retry-attempts: 10
      time-between-connect-error-millis: 1000
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid


eureka:
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://127.0.0.1:11000/eureka
pattern:
  name: 本地环境local