server:
  port: 28080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Taipei
    username: yesee
    password: yesee
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      break-after-acquire-failure: true
      connection-error-retry-attempts: 10
      time-between-connect-error-millis: 1000
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  jpa:
    show-sql: true
    properties: 
      hibernate: 
        format_sql: true

logging: 
  level: 
    org: 
      hibernate: 
        SQL: DEBUG
        
  application:
    name: orderservice
#  cloud:
#    nacos:
#      server-addr: nacos:8848 # nacos服务地址
#      discovery:
#        namespace: 4d6ce343-9e1b-44df-a90f-2cf2b6b3d177 # dev环境
#        ephemeral: false # 是否是临时实例

eureka:
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://127.0.0.1:11000/eureka
#userservice:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: # 指定饥饿加载的服务名称
      - userservice



feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数